name: plotjuggler
version: 3.0.1
summary: The time series visualization tool that you deserve.
description: |
  QT5 based application to display time series in plots,
  using an intuitive "drag and drop" interface.

grade: stable
confinement: strict
base: core18

apps:
  plotjuggler:
    command: opt/ros/melodic/lib/plotjuggler/plotjuggler
    plugs: [network, network-bind, network-manager-observe, opengl, home, removable-media, desktop, desktop-legacy]
    extensions: [kde-neon]

parts:
  plotjuggler:
    plugin: catkin
    source: .
    rosinstall-files: ['snap/local/plotjuggler3.rosinstall']
    include-roscore: false
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - distro-info-data
      - libpulse0

